services:
  db:
    image: mysql:latest
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network
    ports: 
      - "3306:3306"

  flask:
    build: .
    environment:
      - FLASK_APP=app:create_app
      - FLASK_ENV=${FLASK_ENV}
      - DATABASE_URL=${DATABASE_URL}
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db
    networks:
      - app-network
    ports:
    - "5000:5000"

volumes:
  mysql_data:

networks:
  app-network:
