"""Initial migration

Revision ID: 83472eb3b8db
Revises: 
Create Date: 2025-04-10 13:30:14.602867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83472eb3b8db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('client_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('client_email', sa.String(length=255), nullable=True),
    sa.Column('client_phone', sa.String(length=50), nullable=True),
    sa.Column('blob_storage_container_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('contracts',
    sa.Column('contract_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('contract_name', sa.String(length=255), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('document_link', sa.String(length=512), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.client_id'], ),
    sa.PrimaryKeyConstraint('contract_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contracts')
    op.drop_table('clients')
    # ### end Alembic commands ###
